---

- name: Deploy web application
  hosts: applicationserver
  gather_facts: true

  tasks:
    - name: "Deploying web application"
      ansible.builtin.shell:
        cmd: "/usr/bin/echo {{ appkafkamessage }} >/var/www/html/index.html"

    
