---

- name: Deploy web application
  hosts: applicationserver
  gather_facts: true

  tasks:
    - name: "Deploying web application"
      ansible.builtin.debug:
        msg: "{{ appkafkamessage }}"
        
    - name: "Deploying web application"
      ansible.builtin.shell:
        cmd: "/usr/bin/echo '<HTML><BODY><H1>Application server</H1><BR><BR><p>This is the application server required by the organisation.</p></BODY><HTML>' >/var/www/html/index.html"

    
