---

- name: Main Playbook for end to end automation
  hosts: all

  tasks:
    - name: "Create Message on Network Teams queue"
      ansible.builtin.shell:
        cmd: /opt/redhat/amq-broker/broker/bin/artemis producer --destination=networkteam --message="protocol=tcp,port=5432,from=192.168.5.26,to=192.168.5.0/24" --url=tcp://localhost:61616 --message-count=1
