---

- name: "create change control kafka messages"
  hosts: localhost
  become: true
  gather_facts: true
  vars:
    changecontrol_messages_kafka_data: {"Name": Change Request for Network change, "Description": A change is required to open port 5432 from address 192.168.5.51}
    changecontrol_message_send: true

  tasks:
    - name: Install multi python packages required to send kafka message
      ansible.builtin.pip:
        name:
          - kafka-python
          - aiokafka
             
    - name: "Create a change control team kafka message"
      wwt.kafka.kafka_producer:
        host: "192.168.5.25"
        port: "9092"
        topic: "changecontrolteam"
        data: "{{ changecontrol_messages_kafka_data }}"
      when: changecontrol_message_send
