---

- name: "Create Database change control kafka messages"
  hosts: messageserver
  become: true
  vars:
    kafka_server: "192.168.5.29"
    kafka_port: "9092"
    kafka_topic: "changecontrolteam"
    kafka_message: {"Name": Change Request for database change, "Description": A change is required to create a new database}
    kafka_send: true


  tasks:
    - name: Install python3-pip
      ansible.builtin.dnf:
        name: python3-pip
        state: present
        
    - name: Install multi python packages required to send kafka message
      ansible.builtin.pip:
        name:
          - kafka-python
          - aiokafka
             
    - name: "Create a network team kafka message"
      wwt.kafka.kafka_producer:
        host: "{{ kafka_server }}"
        port: "{{ kafka_port }}"
        topic: "{{ kafka_topic }}"
        data: "{{ kafka_message }}"
      when: kafka_send
