---

- name: "Database team playbook"
  hosts: all
  gather_facts: false

  tasks:
    - name: "Download database SQL file"
      ansible.builtin.get_url:
        url: "{{ dbkafkamessage.DB_sql }}"
        dest: /tmp/database.sql
        mode: '0744'

    - name: "Create new Database."
      debug:
        msg: "{{ dbkafkamessage }}"
        
    - name: "Updating the HBA Config for new webserver"
      debug:
        msg: "{{ dbkafkamessage }}"
