---

- name: "Database team playbook"
  hosts: all
  gather_facts: false

  tasks:
    - name: "Download database SQL file"
      ansible.builtin.debug:
        msg: "Download {{ dbkafkamessage.DB_sql }} to dest /tmp/database.sql"

    - name: "Create new Database."
      ansible.builtin.debug:
        msg: "/usr/bin/sudo -u postgres /usr/bin/psql {{ dbkafkamessage.DB_Name }} < /tmp/database.sql"
        
    - name: "Updating the HBA Config for new webserver"
      ansible.builtin.debug:
        msg: "{{ dbkafkamessage }}"
