---

- name: Test Playbook
  hosts: "{{ checkmk_hostname | default('all')}}"

  tasks:
    - name: "Debugging High CPU issues"
      debug:
        msg: "{{checkmk_hostname}} has this message = {{checkmk_message}}"
