---
- name: Create Inventory
  hosts: messageserver

  tasks:
    - name: "Create Dynamic inventory for new server"
      add_host:
        hostname: "{{infrakafkamessage.VM_IP}}"
        groupname: "newvm"

- name: Configure Server
  hosts: newvm
  tasks:
    - name: "Register to Red Hat Subscription"
      ansible.builtin.shell:
        cmd: /usr/sbin/subscription-manager register --username "{{infrateam_rh_username}}" --password "{{infrateam_rh_password}}"
          
    - name: "Install Web server package"
      ansible.builtin.dnf:
        name: "httpd"
        state: present
      when: infrakafkamessage.VM_TYPE == "webserver"
  
    - name: "Open Local Firewall Port 80"
      ansible.posix.firewalld:
        port: 80/tcp
        permanent: true
        state: enabled
        immediate: true
      when: infrakafkamessage.VM_TYPE == "webserver"
    
    - name: "Enable and start web server"
      ansible.builtin.systemd_service:
        name: httpd
        state: started
        enabled: true
      when: infrakafkamessage.VM_TYPE == "webserver" 

    - name: "Enable postgresql 16 module."
      ansible.builtin.shell:
        cmd: dnf module enable postgresql:16 -y
      when: infrakafkamessage.VM_TYPE == "dbserver"
      
    - name: "Install Database server package"
      ansible.builtin.dnf:
        name: "postgresql-server"
        state: present
      when: infrakafkamessage.VM_TYPE == "dbserver"

    - name: "Postgresql setup."
      ansible.builtin.shell:
        cmd: /usr/bin/postgresql-setup --initdb
      when: infrakafkamessage.VM_TYPE == "dbserver"

    - name: "Enable and start database server"
      ansible.builtin.systemd_service:
        name: postgresql
        state: started
        enabled: true
      when: infrakafkamessage.VM_TYPE == "dbserver" 

    - name: "Unregister to Red Hat Subscription"
      ansible.builtin.shell:
        cmd: /usr/sbin/subscription-manager unregister
      
