---

- name: Build A Virtual Machine
  hosts: all
  gather_facts: true

  tasks:
    - name: "Debugging"
      debug:
        msg: "Testing"
    - name: "Debug Message"
      debug:
        msg: "{{ kafkamessage }}"
