---

- name: Build A Virtual Machine
  hosts: all
  gather_facts: true
  vars:
    kafkamessage: "Test Me a message"
    
  tasks:
    - name: "Debugging"
      debug:
        msg: "Testing"
    - name: "Debug Message"
      debug:
        msg: "{{ kafkamessage }}"
