---

- name: Configure Server
  hosts: "{{infrakafkamessage.VM_IP}}"

  tasks:
    - name: "Install Web server package"
      ansible.builtin.dnf:
        name: "httpd"
        state: present
      when: infrakafkamessage.VM_TYPE == "webserver"

    - name: "Install Database server package"
      ansible.builtin.dnf:
        name: "postgresql-server"
        state: present
      when: infrakafkamessage.VM_TYPE == "dbserver"
      
