---
- name: Create Inventory
  hosts: messageserver

  tasks:
    - name: "Create Dynamic inventory for new server"
      add_host:
        hostname: "{{infrakafkamessage.VM_IP}}"
        groupname: "newvm"

- name: Configure Server
  hosts: newvm
  tasks:
    - name: "Install Web server package"
      ansible.builtin.dnf:
        name: "httpd"
        state: present
      when: infrakafkamessage.VM_TYPE == "webserver"

    - name: "Install Database server package"
      ansible.builtin.dnf:
        name: "postgresql-server"
        state: present
      when: infrakafkamessage.VM_TYPE == "dbserver"
      
