---
- name: Create Inventory
  hosts: firewalls

  tasks:
    - name: "Create Dynamic inventory for new server"
      add_host:
        hostname: "{{ kafkamessage.To }}"
        groupname: "newvm"


- name: "Network Team Playbook"
  hosts: newvm
  gather_facts: false
  
  tasks:
    - name: "Opening Ports {{ kafkamessage.Port }} from {{ kafkamessage.From }} to {{ kafkamessage.To }} "
      debug:
        msg: "Opening Ports {{ kafkamessage.Port }} from {{ kafkamessage.From }} to {{ kafkamessage.To }}"
     
    - name: "Open port on server {{ kafkamessage.To }}"
      ansible.posix.firewalld:
        port: "{{ kafkamessage.Port }}/{{ kafkamessage.Protocol }}"
        permanent: true
        state: enabled
        immediate: true
