---

- name: Test Playbook
  hosts: all

  tasks:
    - name: "Debugging"
      debug:
        msg: "Testing"
    - name: "Debug Message"
      debug:
        msg: "{{ job_args.extra_vars.kafkamessage }}"
