---

- name: "Network Team Playbook"
  hosts: all
  gather_facts: false

  tasks:
    - name: "Opening Ports {{ kafkamessage.Port }} from {{ kafkamessage.From }} to {{ kafkamessage.To }} "
      debug:
        msg: "Opening Ports {{ kafkamessage.Port }} from {{ kafkamessage.From }} to {{ kafkamessage.To }}"
     
    - ansible.posix.firewalld:
        port: "{{ kafkamessage.Port }}/{{ kafkamessage.Protocol }}"
        permanent: true
        state: enabled
