---

- name: "create change control kafka messages"
  hosts: 192.168.5.29
  become: true
  vars:
    kafka_server: "192.168.5.29"
    kafka_port: "9092"
    kafka_topic: "changecontrolteam"
    kafka_message: {"Name": Open a new Port to database server, "Description:": Please open port 5432 From server 192.168.122.30 to 192.168.122.20}
    kafka_send: true

  tasks:
    - name: Install python3-pip
      ansible.builtin.dnf:
        name: python3-pip
        state: present
        
    - name: Install multi python packages required to send kafka message
      ansible.builtin.pip:
        name:
          - kafka-python
          - aiokafka
             
    - name: "Create a network team kafka message"
      wwt.kafka.kafka_producer:
        host: "{{ kafka_server }}"
        port: "{{ kafka_port }}"
        topic: "{{ kafka_topic }}"
        data: "{{ kafka_message }}"
      when: kafka_send
