---

- name: Test Playbook
  hosts: all
  gather_facts: false

  tasks:
    - name: "Debugging"
      debug:
        msg: "Testing"
    - name: "Debug Message"
      debug:
        msg: "{{ kafkamessage.From }}"
