- name: Rulebook to do something
  hosts: 192.168.122.101
  gather_facts: false

  sources:
      - ansible.eda.file_watch:
          path: "/testeda/"
          recursive: true 
          ignore_regexes: [ '.*\.o' ]
  rules:
      - name: trigger on new file 
        condition: event.change == 'created' # 'modified'
        action:
           run_job_template:
               name: testplaybook
                                  
      - name: trigger on file deletion 
        condition: event.change == 'deleted' # 'modified'
        action:
           run_job_template:
               name: testplaybook
               
