---
- name: Listen for events on a webhook from CheckMK
  hosts: all
  sources:
    - name: Listen for alerts from CheckMK
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 4999

  rules:
    - name: High CPU Usage Detected
      condition: event.payload.event_title == "[Triggered] CPU Load is high"
      action:
        run_workflow_template:
          name: "checkmkhighcpu"
          organization: "Default"
          job_args:
            extra_vars:
              vm_name: "{{ event.payload.hostname }}"
           retries: 1
           delay: 1

    - name: Web Application Down Detected
      condition: event.payload.event_title == "[Triggered] Web Server is Down"
      action:
        run_workflow_template:
          name: "Automated Response Web Server EDA"
          organization: "Default"
          job_args:
            extra_vars:
              vm_name: "{{ event.payload.hostname }}"

    - name: CheckMK Not Responding
      condition: event.payload.event_title == "[Triggered] Host not reporting data"
      action:
        run_workflow_template:
          name: "Remediate CheckMK"
          organization: "Default"
          job_args:
            extra_vars:
              vm_name: "{{ event.payload.hostname }}"

    - name: See all other checkmk alerts
      condition: event.meta is defined and event.payload.event_title != "[Triggered] CPU Load is high" and event.payload.event_title != "[Triggered] Web Server is Down"  # noqa yaml[line-length]
      action:
        debug:
