---
- name: Rulebook run playbook for database team
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: "192.168.5.29"
        port: "9092"
        group_id: "mygroupid"
        topic: "databaseteam"
        check_hostname: false
        verify_mode: "CERT_NONE"

  rules:
    - name: trigger on new message for database teams
      condition: event.body != ""
      action:
        run_job_template:
          name: databaseteamworkflow
          organization: Default
          job_args:
            extra_vars:
              kafkamessage: "{{ event.body }}"
          retries: 1
          delay: 10
        
