---
- name: Rulebook run playbook for infrastructure team
  hosts: all
  gather_facts: true
  sources:
    - ansible.eda.kafka:
        host: "192.168.5.25"
        port: "9092"
        group_id: "mygroupid"
        topic: "infrastructureteam"
        check_hostname: false
        verify_mode: "CERT_NONE"

  rules:
    - name: trigger on new message for infrastructure teams
      condition: event.body != ""
      action:
        run_job_template:
          name: infrastructureteamplaybook
          organization: Default
          job_args:
            extra_vars:
              fred: "yes sir"
              kafkamessage: "{{ event.body }}"
          retries: 1
          delay: 10
