---
- name: Rulebook run playbook for infrastructure team
  hosts: all
  sources:
    - ansible.eda.kafka:
        host: "192.168.5.29"
        port: "9092"
        topic: "infrastructureteam"
        check_hostname: false
        verify_mode: "CERT_NONE"

  rules:
    - name: trigger on new message for infrastructure teams
      condition: event.body != ""
      action:
        run_workflow_template:
          name: infrastructureteamworkflow
          organization: Default
          job_args:
            extra_vars:
              infrakafkamessage: "{{ event.body }}"
          retries: 1
          delay: 10
