- name: Rulebook run playbook for network team
  hosts: all
  gather_facts: true
  sources:
    - ansible.eda.kafka:
        host: 192.168.5.25
        port: 9092
        topic: networkteam
        check_hostname: False
        verify_mode: CERT_NONE

  rules:
    - name: trigger on new message for network team
      condition: event.message is defined
      action:
        debug:
          msg: "first: {{ events.first }}
