- name: Rulebook run playbook for network team
  hosts: all

  sources:
      - ansible.eda.kafka:
          host: 192.168.5.25
          port: 61616
          topic: networkteam
          check_hostname: False
          verify_mode: CERT_NONE
          sasl_plain_username: amq-broker
          sasl_plain_password: password123
  rules:
      - name: trigger on new message for network team
        condition: event.message != ""
        action:
          run_job_template:
              name: networkteamplaybook
              organization: Default

                
