---
- name: Rulebook run playbook for network team
  hosts: all
  gather_facts: true
  sources:
    - ansible.eda.kafka:
        host: "192.168.5.29"
        port: "9092"
        topic: "networkteam"
        check_hostname: false
        verify_mode: "CERT_NONE"

  rules:
    - name: "trigger on new message for network teams"
      condition: event.body != ""
      action:
        run_job_template:
          name: networkteamplaybook
          organization: Default
          job_args:
            extra_vars:
              kafkamessage: "{{ event.body }}"
          retries: 1
          delay: 10
